services:
  frontend:
    image: ghcr.io/aallaann1/mailalert-frontend:latest
    container_name: mailalert-frontend
    restart: always
    ports:
      - 3005:3000
    env_file:
      - .env
    environment:
      # L'URL de l'API Backend pour le Frontend
      - VITE_API_URL=http://192.168.1.139:8005
    depends_on:
      - backend

  backend:
    image: ghcr.io/aallaann1/mailalert-backend:latest
    container_name: mailalert-backend
    restart: always
    ports:
      - 8005:8000
    env_file:
      - .env
    volumes:
      - ./data:/app/data
